export const POST_NOTE_SUCCESS = "POST_NOTE_SUCCESS"
export const POST_NOTE_ERROR = "POST_NOTE_SUCCESS"

export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS"
export const GET_NOTE_ERROR = "GET_NOTE_ERROR"

export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR"

export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTE_ERROR = "UPDATE_NOTE_ERROR"

export const GET_COLOR_SUCCESS = "GET_COLOR_SUCCESS"
export const GET_COLOR_ERROR = "GET_COLOR_ERROR"
